name:                cellout
version:             0.1.0.0
github:              "ivanov/cellout"
license:             BSD3
author:              "Paul Ivanov"
maintainer:          "pi@berkeley.edu"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ivanov/cellout#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cellout-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cellout

tests:
  cellout-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cellout
